(function($){
	$(document).ready(function(){
							
var a0={
slide_heading:'Today Grand Opening',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Oregano',
slide_heading_size:'80px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#FFFF66',
slide_heading_margin_top:'20px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'07-02-2015',
slide_text_font:'Oregano',
slide_text_size:'26px',
slide_text_font_weight:'300',
slide_text_color:'#FFFFFF',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Get Started',
button_margin_top:'0px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#7799CC',
background_image:'Henry_Marion.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'20',
background_image_blur:'0px',
icon:'cloud',
style_id:'preset_preset_376',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
};

var a1={
slide_heading:'Just Simple',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Satisfy',
slide_heading_size:'80px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#444444',
slide_heading_margin_top:'20px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'Join on or before 12-2-2015',
slide_text_font:'Gruppo',
slide_text_size:'26px',
slide_text_font_weight:'300',
slide_text_color:'#DD3333',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Get Started',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#EEEEEE',
background_image:'mypad.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'20',
background_image_blur:'0px',
icon:'chat',
style_id:'preset_245',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a2={
slide_heading:'Spot 3 differences<br>in the Spykar shirt below',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Sacramento',
slide_heading_size:'80px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#FFffff',
slide_heading_margin_top:'20px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'',
slide_text_font:'Oregano',
slide_text_size:'26px',
slide_text_font_weight:'300',
slide_text_color:'#FFFFFF',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Get Started',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#ff0000',
background_image:'Henry_Marion.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'20',
background_image_blur:'0px',
icon:'cloud',
style_id:'preset_239',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a3={
slide_heading:'FLAT<br>55%<br>OFF',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Anton',
slide_heading_size:'72px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#FF1133',
slide_heading_margin_top:'20px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'ON PURCHASE OF<br>Rs. 999 & ABOVE',
slide_text_font:'Arial',
slide_text_size:'26px',
slide_text_font_weight:'300',
slide_text_color:'#DD1133',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Shop Now!',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#99DDCC',
background_image:'no',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'20',
background_image_blur:'0px',
icon:'tag',
style_id:'preset_245',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a4={
slide_heading:'ADDITIONAL<br>14% OFF',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Ultra',
slide_heading_size:'72px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#5577FF',
slide_heading_margin_top:'20px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'MAX DISCOUNT Rs. 300<br>NOT VALID ON ELECTRONICS',
slide_text_font:'sans-serif',
slide_text_size:'18px',
slide_text_font_weight:'300',
slide_text_color:'#000000',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Shop Now!',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#FFBB00',
background_image:'no',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'20',
background_image_blur:'0px',
icon:'tag',
style_id:'preset_215',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a5={
slide_heading:'FLAT<br>40% OFF<span style=',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Anton',
slide_heading_size:'100px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#222222',
slide_heading_margin_top:'20px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'*T & C Apply',
slide_text_font:'sans-serif',
slide_text_size:'18px',
slide_text_font_weight:'300',
slide_text_color:'#000000',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Shop Now!',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#FFBB00',
background_image:'dust.png',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'70',
background_image_blur:'0px',
icon:'tag',
style_id:'preset_239',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a6={
slide_heading:'FLAT<br>55%<br>OFF',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Rock Salt',
slide_heading_size:'72px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#ffffff',
slide_heading_margin_top:'20px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'ON PURCHASE OF<br>Rs. 999 & ABOVE',
slide_text_font:'Exo',
slide_text_size:'26px',
slide_text_font_weight:'300',
slide_text_color:'#dddddd',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Shop Now!',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#99DDCC',
background_image:'jelly_fish.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'100',
background_image_blur:'0px',
icon:'tag',
style_id:'preset_245',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a7={
slide_heading:'Mexican Days are here!<br>Get 20% off. ',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Oswald',
slide_heading_size:'66px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#ffffff',
slide_heading_margin_top:'20px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'',
slide_text_font:'Exo',
slide_text_size:'26px',
slide_text_font_weight:'300',
slide_text_color:'#ffffff',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Connect and Visit',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#000000',
background_image:'coffee_food.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'80',
background_image_blur:'0px',
icon:'tag',
style_id:'preset_247',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a8={
slide_heading:'Creative<br>Stationary',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Sacramento',
slide_heading_size:'80px',
slide_heading_font_weight:'300',
slide_heading_line_height:'0.9em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#111111',
slide_heading_margin_top:'170px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'',
slide_text_font:'Arial',
slide_text_size:'8px',
slide_text_font_weight:'300',
slide_text_color:'',
slide_text_margin_top:'10px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Buy Now',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#FFFF66',
background_image:'Creative-Stationary.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'100',
background_image_blur:'0px',
icon:'no',
style_id:'preset_245',
frame_height:'500px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a9={
slide_heading:'Design,<br>Code & Photography.',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Arial',
slide_heading_size:'52px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'',
slide_heading_margin_top:'70px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'Individual communications solutions.',
slide_text_font:'sans-serif',
slide_text_size:'28px',
slide_text_font_weight:'300',
slide_text_color:'#999999',
slide_text_margin_top:'10px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Get Started',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#000000',
background_image:'vintage.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'30',
background_image_blur:'0px',
icon:'no',
style_id:'preset_643',
frame_height:'500px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a10={
slide_heading:'FREE PHOTOS',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Oswald',
slide_heading_size:'66px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#slide_heading_color',
slide_heading_margin_top:'10px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'A fresh pack to your inbox<br>each month, with awesome<br>stories to match.',
slide_text_font:'Arial',
slide_text_size:'32px',
slide_text_font_weight:'300',
slide_text_color:'#slide_text_color',
slide_text_margin_top:'10px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'LET\'S GO',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#555555',
background_image:'black_bg.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'80',
background_image_blur:'0px',
icon:'no',
style_id:'preset_641',
frame_height:'null',
}
var a11={
slide_heading:'<span style="font-weight:300">KISSmetrics gives you the insights you need</span>',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Open Sans',
slide_heading_size:'28px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'',
slide_heading_margin_top:'80px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'<span style="font-weight:300">to optimize your marketing.</span>',
slide_text_font:'Open Sans',
slide_text_size:'28px',
slide_text_font_weight:'300',
slide_text_color:'#FFDD33',
slide_text_margin_top:'10px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Know More',
button_margin_top:'20px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#33BB33',
background_image:'triangles.png',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'100',
background_image_blur:'0px',
icon:'no',
style_id:'preset_636',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a12={
slide_heading:'If you don\'t<br>want anyone<br>to find out, ',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Neucha',
slide_heading_size:'44px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'0px',
slide_heading_color:'#eeeeee',
slide_heading_margin_top:'70px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'don\'t do it.',
slide_text_font:'Neucha',
slide_text_size:'44px',
slide_text_font_weight:'300',
slide_text_color:'#99BB66',
slide_text_margin_top:'0px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Chinese Proverb',
button_margin_top:'30px',
button_margin_bottom:'30px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#223045',
background_image:'no',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'0',
background_image_blur:'0px',
icon:'no',
style_id:'preset_721',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a13={
slide_heading:'Telerik Kendo UI',
slide_heading_2:'',
slide_heading_3:'',
slide_heading_font:'Open Sans',
slide_heading_size:'52px',
slide_heading_font_weight:'700',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'-3px',
slide_heading_color:'',
slide_heading_margin_top:'40px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'Everything You Need to Build Sites and Apps<br>With Pure JavaScript and HTML5',
slide_text_font:'Open Sans',
slide_text_size:'18px',
slide_text_font_weight:'300',
slide_text_color:'',
slide_text_margin_top:'30px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'Get Started Now',
button_margin_top:'40px',
button_margin_bottom:'70px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#111111',
background_image:'bottom_lighting.png',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'100',
background_image_blur:'0px',
icon:'no',
style_id:'preset_748',
frame_height:'300px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}
var a14={
slide_heading:'Social OS',
slide_heading_2:'<strong>People</strong>Browser',
slide_heading_3:'',
slide_heading_font:'Open Sans',
slide_heading_size:'52px',
slide_heading_font_weight:'300',
slide_heading_line_height:'1.2em',
slide_heading_letter_spacing:'-4px',
slide_heading_color:'',
slide_heading_margin_top:'100px',
slide_heading_margin_left:'0px',
slide_heading_margin_right:'0px',
slide_heading_padding:'0px',
slide_heading_border_width:'0px',
slide_heading_border_color:'',
slide_heading_background_color:'',
slide_heading_shadow_distance:'0px',
slide_text:'Social Networks for<br>the Online Enterprise',
slide_text_font:'Open Sans',
slide_text_size:'26px',
slide_text_font_weight:'300',
slide_text_color:'',
slide_text_margin_top:'20px',
slide_text_margin_left:'0px',
slide_text_margin_right:'0px',
button_text:'slideshare.net',
button_margin_top:'30px',
button_margin_bottom:'100px',
slide_footer_text:'',
slide_footer_padding:'0px',
slide_footer_text_size:'8px',
background_color:'#333333',
background_image:'forest1.jpg',
background_custom_image:'',
background_repeat_image:'no',
background_image_opacity:'30',
background_image_blur:'0px',
icon:'no',
style_id:'preset_752',
frame_height:'400px',
frame_margin_left:'0px',
frame_margin_right:'0px',
}

wpi_create("0","Sky White",a0);
wpi_create("1","Gray Black",a1);
wpi_create("2","Red White",a2);
wpi_create("3","Sky Red",a3);
wpi_create("4","Yellow Sky",a4);
wpi_create("5","Yellow Black",a5);
wpi_create("6","Jelly Fish",a6);
wpi_create("7","Mexican Days",a7);
wpi_create("8","Mexican Days",a8);
wpi_create("9","Mexican Days",a9);
wpi_create("10","Mexican Days",a10);
wpi_create("11","KISSmetrics",a11);
wpi_create("12","If you don't",a12);
wpi_create("13","Telerik",a13);
wpi_create("14","Social Os",a14);

		function wpi_create(index, name, args){
			$(document).create_sli_presets(index, name, args);
		};
		
	});
})(jQuery);